CREATE TABLE users (
    id BIGINT PRIMARY KEY NOT NULL,
    username TEXT NOT NULL DEFAULT '',
    password TEXT NOT NULL DEFAULT '',
    roles JSON NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE plan (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    uid BIGINT NOT NULL DEFAULT -1,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL DEFAULT ''
);

CREATE TABLE dynamic (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    uid BIGINT NOT NULL DEFAULT -1,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL DEFAULT '',
    replyid BIGINT NOT NULL DEFAULT -1
);
