CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    username VARCHAR(20) NOT NULL DEFAULT '',
    password VARCHAR(256) NOT NULL DEFAULT ''
);

CREATE TABLE plan (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    uid BIGINT NOT NULL DEFAULT -1,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL DEFAULT ''
);

CREATE TABLE dynamic (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    uid BIGINT NOT NULL DEFAULT -1,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL DEFAULT '',
    replyid BIGINT NOT NULL DEFAULT -1
);
